// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['backend']['App']['ClearHistory']();
}

export function DeleteOneHistory(arg1) {
  return window['go']['backend']['App']['DeleteOneHistory'](arg1);
}

export function Detect(arg1) {
  return window['go']['backend']['App']['Detect'](arg1);
}

export function GetHistory(arg1, arg2) {
  return window['go']['backend']['App']['GetHistory'](arg1, arg2);
}

export function GormDB() {
  return window['go']['backend']['App']['GormDB']();
}

export function UploadImage(arg1, arg2) {
  return window['go']['backend']['App']['UploadImage'](arg1, arg2);
}
