// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {gorm} from '../models';

export function ClearHistory():Promise<backend.Response>;

export function DeleteOneHistory(arg1:number):Promise<backend.Response>;

export function Detect(arg1:string):Promise<backend.Response>;

export function GetHistory(arg1:number,arg2:number):Promise<backend.Response>;

export function GormDB():Promise<gorm.DB>;

export function UploadImage(arg1:Array<number>,arg2:string):Promise<backend.Response>;
