// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {gorm} from '../models';

export function ClearHistory():Promise<main.Response>;

export function DeleteOneHistory(arg1:number):Promise<main.Response>;

export function Detect(arg1:string):Promise<main.Response>;

export function GetHistory(arg1:number,arg2:number):Promise<main.Response>;

export function GetImage(arg1:string):Promise<main.Response>;

export function GormDB():Promise<gorm.DB>;

export function Greet(arg1:string):Promise<string>;

export function UploadImage(arg1:Array<number>,arg2:string):Promise<main.Response>;
