// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOneHistory(arg1) {
  return window['go']['main']['App']['DeleteOneHistory'](arg1);
}

export function Detect(arg1) {
  return window['go']['main']['App']['Detect'](arg1);
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GormDB() {
  return window['go']['main']['App']['GormDB']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
