// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImage(arg1:string):Promise<main.ImageResult>;

export function Greet(arg1:string):Promise<string>;

export function Login():Promise<string>;

export function Register():Promise<string>;

export function UploadImage(arg1:Array<number>,arg2:string):Promise<main.ImageResult>;
