#训练多少轮
epoch = 50

#学习率
lr = 0.0005

#一轮多少张图片
batch_size = 64

#训练图片输入尺寸
input_size = 128

#分类
label_name = [
    "abyssinian",
    "cyprus",
    "lykoi",
    "donskoy",
    "chausie",
    "european_shorthair",
    "turkish_van",
    "pixie_bob",
    "ragdoll",
    "german_rex",
    "american_shorthair",
    "sokoke",
    "khao_manee",
    "thai",
    "cymric",
    "oriental_shorthair",
    "cornish_rex",
    "burmese",
    "savannah",
    "american_wirehair",
    "peterbald",
    "karelian_bobtail",
    "tonkinese",
    "balinese",
    "japanese_bobtail",
    "nebelung",
    "selkirk_rex",
    "persian",
    "manx",
    "himalayan",
    "munchkin",
    "bengal",
    "turkish_angora",
    "vankedisi",
    "scottish_fold",
    "egyptian_mau",
    "ocicat",
    "ragamuffin",
    "serengeti",
    "british_shorthair",
    "toyger",
    "siberian",
    "havana_brown",
    "exotic_shorthair",
    "bombay",
    "korat",
    "safari",
    "american_bobtail",
    "mekong_bobtail",
    "korean_bobtail",
    "siamese",
    "somali",
    "devon_rex",
    "american_curl",
    "ural_rex",
    "singapura",
    "ukrainian_levkoy",
    "maine_coon",
    "birman",
    "oregon_rex",
    "kurilian_bobtail",
    "laperm",
    "sphynx",
    "chartreux",
    "russian_blue",
    "norwegian_forest_cat",
]